spring.application.name=desafio-criptografia

spring.datasource.url=jdbc:postgresql://localhost:5431/db_criptografia
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update